### ISSUE TITLE
Working with Django 1.6

### ISSUE THREAD

**Issue by jamc17** [lionheart/django-pyodbc#33]
I'm working on Django 1.6 and django-pyodbc but don't work on Mac.

FreeTDS and unixODBC is working very well but when I install django-pyodbc and configure 'ENGINE': "django_pyodbc", and do ./manage.py runserver it's displays:

django.core.exceptions.ImproperlyConfigured: 'django_pyodbc' isn't an available database backend. 
Try using django.db.backends.XXX, where XXX is one of
    'dummy', 'mysql', 'oracle', 'postgresql', 'postgresql_psycopg2', 'sqlite3'
Error was: cannot import name connection```

any way to fix this please?

**Comment by jfabiani** [comment]
What has to be changed to work with django 1.8.x?  There is no
from django.db.backends import BaseDatabaseWrapper, ...

**Comment by quetzaluz** [comment]
I checked the code and it looks like we have an update that makes this backwards compatible:
```
try:
    from django.db.backends.base.base import BaseDatabaseWrapper
    from django.db.backends.base.features import  BaseDatabaseFeatures
    from django.db.backends.base.validation import BaseDatabaseValidation
except ImportError:
    # import location prior to Django 1.8
    from django.db.backends import BaseDatabaseWrapper, BaseDatabaseFeatures, BaseDatabaseValidation
```

Perhaps this can now be closed?

**Comment by RossRogers** [comment]
Per @quetzaluz comment, seems to be resolved.  Closing.  Please re-open if I am mistaken.
